### ISSUE TITLE
Add link Placeholder in README file

### ISSUE THREAD

**Issue by Yash-Kavaiya** [Yash-Kavaiya/CampusX-courses#24]
@arv-anshul Can you include add link placeholder of each courses in main README file

**Comment by arv-anshul** [comment]
> Can you include add link placeholder of each courses in main README file

**Which link should I put there?**

- [ ] Official Course's Link
- [ ] Link of the course's folder of this repository.

**Comment by Yash-Kavaiya** [comment]
2. Link of the course's folder of this repository.

**Comment by arv-anshul** [comment]
I'm doing the work but I found it hard because:

1. Folder names are too large.
2. Folder names contains `<space>` in between.
3. Folder names contains special characters like `()`.

This is bad and doesn't well suited as folder names.

---

Instead we can define a pattern/convention for folder naming like `<instructorName>-<short-course-name>`

> [!NOTE]
>
> `<instructorName>` should be of one word and doesn't contains an `-` or `_`.
> `<short-course-name>` should be `-` separated and doesn't have more 3-5 words.

**Comment by arv-anshul** [comment]
Hey, we can discuss the problem here. Why did you closed the issue and PR 😞.

**I am ready to make possible changes.**
